import type { Metadata } from "next";
import "./globals.css";
import type { ReactNode } from 'react';
import Header from "@/components/Header";
import Footer from "@/components/Footer";
export const metadata: Metadata = {
  title: "My Portfolio",
  description:
    "Generated by create next app. Frontend Portfolio built with Next.js, TypeScript, and Tailwind CSS",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-black text-white transition-colors duration-300 text-sm md:text-base">
        <Header />
      <main className="px-4 sm:px-6 md:px-16 py-4 md:py-8">{children}</main>

      </body>
    </html>
  );
}